#!/usr/bin/env bash
#this is comment
while IFS=: read -r username password uid gid userinfo homedir shell; do
    echo "The user $username is part of the $gid gang, lives in $homedir and rides $shell. USER ID's place is protected by the passcode $password, more info about the user here: $userinfo"
done < /etc/passwd

