#!/usr/bin/env bash
# Display time from 0:1 to 12:59 using while loops, formatted as expected

hour=0

while [ $hour -le 12 ]; do
    echo "Hour: $hour"
    minute=1
    while [ $minute -le 59 ]; do
        echo "$minute"
        ((minute++))
    done
    ((hour++))
done | head -n 70
