#!/usr/bin/env bash
# Check information about the school file

file="school"

if [ -e "$file" ]; then
    echo "school file exists"

    # Check if the file is empty
    if [ ! -s "$file" ]; then
        echo "school file is empty"
    else
        echo "school file is not empty"
    fi

    # Check if it is a regular file
    if [ -f "$file" ]; then
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
